version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "@chromatic-com/*"
          - "storybook"
          - "storybook-*"
          - "@whitespace/storybook-addon-html"
      svelte:
        patterns:
          - "svelte"
          - "svelte-*"
          - "@sveltejs/*"
      tailwind:
        patterns:
          - "tailwind*"
          - "@tailwindcss/*"
          - "tw-animate-css"
      lint-and-format:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript*"
          - "typescript-eslint"
          - "prettier*"
          - "globals"
